# Generated by Django 5.2.8 on 2026-07-21 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('plastic', 'Plastic Recycling'), ('paper', 'Paper & Cardboard'), ('metal', 'Metal Scrap'), ('glass', 'Glass'), ('organic', 'Organic Waste'), ('all', 'General Waste')], default='all', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('glass', 'Glass'), ('organic', 'Organic')], max_length=40)),
                ('location', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('preferred_pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('paid', 'paid'), ('approved', 'approved'), ('collected', 'collected'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Describe the waste you want collected.')),
                ('assigned_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to='WasteApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
